import { quoteItem } from 'types/quoteList';

export const mockData: quoteItem[] = [
  {
    id: 0,
    content: 'This is the first post content.',
    author: 'Alice',
    registrant: 'alice123',
    tag: ['news', 'updates'],
    likes: 5,
    comments: ['Great post!', 'Very informative.'],
    created_at: new Date().toLocaleDateString(),
  },
  {
    id: 1,
    content: 'Here is some interesting content.',
    author: 'Bob',
    registrant: 'bob_the_builder',
    tag: ['fun'],
    likes: 12,
    comments: ['Loved it!', 'Can you post more like this?'],
    created_at: new Date().toLocaleDateString(),
  },
  {
    id: 2,
    content: 'An update about the upcoming event.',
    author: 'Charlie',
    registrant: 'charlie_events',
    tag: ['events', 'updates', 'announcements'],
    likes: 8,
    comments: ['Looking forward to it!', 'Thanks for the info.'],
    created_at: new Date().toLocaleDateString(),
  },
  {
    id: 3,
    content: 'Tips and tricks for better productivity.',
    author: 'David',
    registrant: 'david_productivity',
    tag: ['tips', 'productivity', 'work'],
    likes: 20,
    comments: ['Very useful tips!', 'Thanks for sharing.', 'Amazing!'],
    created_at: new Date().toLocaleDateString(),
  },
  {
    id: 4,
    content: 'A review of the latest gadget.',
    author: 'Eve',
    registrant: 'eve_gadgets',
    tag: ['reviews', 'gadgets'],
    likes: 15,
    comments: ['I want to buy this now!', 'Great review.'],
    created_at: new Date().toLocaleDateString(),
  },
  {
    id: 5,
    content: 'Exploring new places to travel.',
    author: 'Frank',
    registrant: 'frank_travels',
    tag: ['travel', 'exploration'],
    likes: 18,
    comments: ['Amazing places!', 'I want to go there too.'],
    created_at: new Date().toLocaleDateString(),
  },
  {
    id: 6,
    content: 'Healthy recipes for a better lifestyle.',
    author: 'Grace',
    registrant: 'grace_cooking',
    tag: ['health', 'recipes', 'food'],
    likes: 25,
    comments: ['Yummy!', 'I will try this recipe.'],
    created_at: new Date().toLocaleDateString(),
  },
  {
    id: 7,
    content: 'Understanding the basics of programming.',
    author: 'Hank',
    registrant: 'hank_programming',
    tag: ['education', 'programming'],
    likes: 10,
    comments: ['Very helpful for beginners.', 'Thanks for explaining so well.'],
    created_at: new Date().toLocaleDateString(),
  },
  {
    id: 8,
    content: 'Latest trends in fashion.',
    author: 'Ivy',
    registrant: 'ivy_fashion',
    tag: ['fashion', 'trends'],
    likes: 22,
    comments: ['I love the new trends!', 'Great fashion tips.', 'Awesome!'],
    created_at: new Date().toLocaleDateString(),
  },
  {
    id: 9,
    content: 'How to stay fit during quarantine.',
    author: 'Jack',
    registrant: 'jack_fitness',
    tag: ['fitness', 'health'],
    likes: 30,
    comments: ['Thanks for the motivation!', 'These tips are very helpful.'],
    created_at: new Date().toLocaleDateString(),
  },
  {
    id: 10,
    content: 'Top 10 programming languages to learn in 2024.',
    author: 'Kevin',
    registrant: 'kevin_code',
    tag: ['programming', 'education', 'tech'],
    likes: 40,
    comments: [
      'Very informative.',
      'Great list!',
      'Agreed on these languages.',
    ],
    created_at: new Date().toLocaleDateString(),
  },
  {
    id: 11,
    content: 'The ultimate guide to online marketing.',
    author: 'Laura',
    registrant: 'laura_marketing',
    tag: ['marketing', 'guide'],
    likes: 25,
    comments: ['Very detailed guide.', 'Thanks for sharing.'],
    created_at: new Date().toLocaleDateString(),
  },
  {
    id: 12,
    content: 'Best practices for remote work.',
    author: 'Mike',
    registrant: 'mike_remote',
    tag: ['work', 'remote', 'productivity'],
    likes: 18,
    comments: ['Very useful tips!', 'Will implement these.', 'Great advice.'],
    created_at: new Date().toLocaleDateString(),
  },
  {
    id: 13,
    content: 'Understanding blockchain technology.',
    author: 'Nina',
    registrant: 'nina_blockchain',
    tag: ['blockchain', 'tech'],
    likes: 35,
    comments: ['Very informative.', 'Great article on blockchain.'],
    created_at: new Date().toLocaleDateString(),
  },
  {
    id: 14,
    content: 'A guide to healthy eating.',
    author: 'Oscar',
    registrant: 'oscar_health',
    tag: ['health', 'food', 'guide'],
    likes: 28,
    comments: ['Very helpful!', 'I will follow these tips.'],
    created_at: new Date().toLocaleDateString(),
  },
  {
    id: 15,
    content: 'Tips for effective time management.',
    author: 'Paul',
    registrant: 'paul_time',
    tag: ['time management', 'productivity'],
    likes: 22,
    comments: ['Great tips!', 'This is very helpful.'],
    created_at: new Date().toLocaleDateString(),
  },
  {
    id: 16,
    content: 'Exploring the world of AI.',
    author: 'Quinn',
    registrant: 'quinn_ai',
    tag: ['AI', 'tech'],
    likes: 33,
    comments: ['Amazing article!', 'AI is the future.', 'Very informative.'],
    created_at: new Date().toLocaleDateString(),
  },
  {
    id: 17,
    content: 'A beginner’s guide to photography.',
    author: 'Rachel',
    registrant: 'rachel_photos',
    tag: ['photography', 'guide'],
    likes: 26,
    comments: ['Very helpful for beginners.', 'Great tips!'],
    created_at: new Date().toLocaleDateString(),
  },
  {
    id: 18,
    content: 'Understanding personal finance.',
    author: 'Sam',
    registrant: 'sam_finance',
    tag: ['finance', 'personal finance', 'money'],
    likes: 21,
    comments: ['Very useful information.', 'Thanks for the tips.'],
    created_at: new Date().toLocaleDateString(),
  },
  {
    id: 19,
    content: 'How to start a successful blog.',
    author: 'Tina',
    registrant: 'tina_blog',
    tag: ['blogging', 'guide'],
    likes: 29,
    comments: ['Very detailed guide.', 'This is very helpful.'],
    created_at: new Date().toLocaleDateString(),
  },
  {
    id: 20,
    content: 'Mastering the art of public speaking.',
    author: 'Uma',
    registrant: 'uma_speaker',
    tag: ['public speaking', 'self-improvement'],
    likes: 34,
    comments: ['Very inspiring!', 'I will use these tips.'],
    created_at: new Date().toLocaleDateString(),
  },
  {
    id: 21,
    content: 'A comprehensive guide to yoga.',
    author: 'Vince',
    registrant: 'vince_yoga',
    tag: ['yoga', 'health'],
    likes: 28,
    comments: ['Great guide!', 'Very helpful for beginners.'],
    created_at: new Date().toLocaleDateString(),
  },
  {
    id: 22,
    content: 'Exploring different cultures through food.',
    author: 'Wendy',
    registrant: 'wendy_foodie',
    tag: ['food', 'culture'],
    likes: 19,
    comments: ['I love trying new cuisines!', 'Great recommendations.'],
    created_at: new Date().toLocaleDateString(),
  },
  {
    id: 23,
    content: 'The benefits of meditation.',
    author: 'Xander',
    registrant: 'xander_meditates',
    tag: ['meditation', 'health', 'mindfulness'],
    likes: 31,
    comments: ['Meditation has changed my life!', 'Very informative article.'],
    created_at: new Date().toLocaleDateString(),
  },
  {
    id: 24,
    content: 'A travel guide to Japan.',
    author: 'Yara',
    registrant: 'yara_travels',
    tag: ['travel', 'Japan'],
    likes: 27,
    comments: ['I want to visit Japan now!', 'Great guide.'],
    created_at: new Date().toLocaleDateString(),
  },
  {
    id: 25,
    content: 'The essentials of cybersecurity.',
    author: 'Zane',
    registrant: 'zane_security',
    tag: ['cybersecurity', 'tech', 'essentials'],
    likes: 38,
    comments: [
      'Very important information.',
      'Great tips for staying safe online.',
    ],
    created_at: new Date().toLocaleDateString(),
  },
  {
    id: 26,
    content: 'The art of minimalism.',
    author: 'Ava',
    registrant: 'ava_minimalist',
    tag: ['minimalism', 'lifestyle'],
    likes: 22,
    comments: ['Love the simplicity!', 'I need to declutter my life.'],
    created_at: new Date().toLocaleDateString(),
  },
  {
    id: 27,
    content: 'How to start investing in stocks.',
    author: 'Brian',
    registrant: 'brian_investor',
    tag: ['investing', 'finance', 'stocks'],
    likes: 29,
    comments: ['Great advice for beginners.', 'Very informative.'],
    created_at: new Date().toLocaleDateString(),
  },
  {
    id: 28,
    content: 'A beginner’s guide to cooking.',
    author: 'Clara',
    registrant: 'clara_cooks',
    tag: ['cooking', 'recipes', 'guide'],
    likes: 24,
    comments: [
      'I’m excited to try these recipes!',
      'Very helpful for beginners.',
    ],
    created_at: new Date().toLocaleDateString(),
  },
  {
    id: 29,
    content: 'The future of renewable energy.',
    author: 'Derek',
    registrant: 'derek_energy',
    tag: ['renewable energy', 'tech', 'future'],
    likes: 34,
    comments: ['Very promising!', 'We need more renewable energy.'],
    created_at: new Date().toLocaleDateString(),
  },
];
